language: node_js
node_js:
  - "5.6.0"

before_install:
  - npm install -g npm
  - npm install -g bower

before_script:
  - npm install -g gulp

script:
  - gulp jshint
  - gulp jscs
  - gulp test:client

after_script:
  - codeclimate-test-reporter < ./coverage/report-lcov/lcov.info
  
notifications:
  slack: syn-silobusters:qjMCRvAkoq32QFyUP9FvQj0u
